---
- name: CI Pipeline Setup with Jenkins
  hosts: aws
  become: yes

  tasks:
    - name: Update and upgrade the server
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
          - maven
          - python3
          - python3-pip
          - mysql-server
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes